Repository redBorder/cookbook-postgresql, pull requests merged in 2023-12, with the labels that each got.

#9 Release 0.1.5
  packaging/rpm/cookbook-postgresql.spec
  resources/metadata.rb
Labels: kind/documentation, size/XS

#6 add grant access for pg_hba
  resources/templates/default/pg_hba.conf.erb
Labels: size/S

#10 Release 0.1.6
  packaging/rpm/cookbook-postgresql.spec
  resources/metadata.rb
Labels: kind/documentation, size/XS

#7 add internal services for sync network
  resources/providers/config.rb
  resources/resources/config.rb
Labels: size/S, kind/feature

#11 Release 0.1.7
  packaging/rpm/cookbook-postgresql.spec
  resources/metadata.rb
Labels: kind/documentation, size/XS
